name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [8.1]
    name: PHP ${{ matrix.php-versions }} Test on ubuntu latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Check PHP
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phptan
        run: composer run-script phpstan

      - name: Run test suite
        run: composer run-script test